# fly.toml app configuration file generated for chatopia-server on 2023-05-29T14:11:03-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chatopia-server"
primary_region = "gru"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
